from pathlib import Path
from typing import Any, Literal
import pandas as pd
import json
import plotly.graph_objects as go
import plotly.express as px



tag_tasks = 'tasks'

tag_task_name = "name"
tag_task_id = "id"
tag_task_owner = "owner"
tag_date_start = "date_start_calcd"
tag_date_fin = "date_fin_calcd"
tag_caldays_needed = "calender_days_needed"

tag_dep_start = "name_dependency_start"
tag_typ_start = "typ_start"
tag_lag_start = "lag_start"
tag_dep_fin = "name_dependency_fin"
tag_typ_fin = "typ_fin"
tag_preempt_fin = "preempt_fin"
tag_description = "description"
tag_flag_delay = "flag_delay"

#derived
tag_task_label = "task_label"

#for control
tag_source_order = "_source_order"
tag_owner_rank = '_owner_rank'
tag_task_y = '_task_y'



def load_gantt_json(json_path: str|Path)->dict[str, Any]:
    """Load the input JSON file"""
    path = Path(json_path)
    with path.open('r', encoding='utf-8') as file:
        data = json.load(file)
    if tag_tasks not in data:
        raise ValueError('"tasks" not in the JSON file.')
    if not isinstance(data[tag_tasks], list):
        raise TypeError('"tasks" has to be an array.')
    return data


def prepare_dataframe(data: dict[str, Any]) -> pd.DataFrame:
    df = pd.DataFrame(data[tag_tasks])
    required_columns = [
        tag_task_id, tag_task_name, tag_task_owner, tag_date_start, tag_date_fin
    ]
    missing_columns = [c for c in required_columns if c not in df.columns]
    if missing_columns:
        raise ValueError("Missing mandatory items: "+",".join(missing_columns))

    df[tag_date_start] = pd.to_datetime(df[tag_date_start], format=r"%Y-%m-%d", errors="raise")

    invalid_dates=df[tag_date_fin] < df[tag_date_start]
    if invalid_dates.any():
        invalid_ids = df.loc[invalid_dates, tag_task_id].tolist()
        raise ValueError('The following tasks have invalid datings: '+ ','.join(map(str,invalid_ids)))

    optional_defalults = {
        tag_dep_start:None,
        tag_typ_start:None,
        tag_lag_start:0,
        tag_dep_fin:None,
        tag_typ_fin:None,
        tag_preempt_fin:0,
        tag_description:None,
        tag_flag_delay:False
    }

    for column, default_value in optional_defalults.item():
        if column not in df.columns:
            df[column] = default_value

    df[tag_lag_start] = pd.to_numeric(df[tag_lag_start], errors='coerce').fillna(0).astype(int)
    df[tag_preempt_fin] = pd.to_numeric(df[tag_preempt_fin], errors='coerce').fillna(0).astype(int)
    df[tag_task_owner] = df[tag_task_owner].fillna('No owner set').astype(str)
    df[tag_task_label] = df[tag_task_id].astype(str)+' '+df[tag_task_name].astype(str)

    #dupulication dropped means the initial order of the owners is used as the rank of owners hereafter
    df[tag_source_order] = range(len(df))
    owner_order = df[tag_task_owner].drop_duplicates().tolist()
    owner_rank = {owner: i for i, owner in enumerate(owner_order)}
    df[tag_owner_rank] = df[tag_task_owner].map(owner_rank)
    df = df.sort_values([tag_owner_rank, tag_source_order], kind='stable').reset_index(drop=True)

    #Setting Y axis for each task (and organization)
    lane_gap = 0.9
    current_y = 0.0
    task_y: list[float] = []
    previous_owner: str|None = None
    for owner in df[tag_task_owner]:
        if previous_owner is not None and owner != previous_owner:
            current_y += lane_gap
        task_y.append(current_y)
        current_y += 1.0
        previous_owner = owner
    df[tag_task_y] = task_y

    return df

def add_swimlanes(
        fig: go.Figure,
        df: pd.DataFrame,
        date_freq: Literal['MS', '14D', '7D'] = 'MS',
        date_format:str=r'%Y-%m-%d'
) -> None:
    """
    Prepares a swim lane for each action owner.

    Action:
    1. Sets up a background band for each organization.
    2. Draws a border line at the bottom of each swim lane.
    3. Puts the organization name on the left.
    4. Puts a date scale at the bottom of each swim lane.

    Parameter
    ---------------
    fig:
        Plotly figure to be built.
        
    df:
        A DataFrame object generated by prepare_dataframe().
        This method requires columns corresponding to tag_task_owner, tag_task_y, tag_date_start, tag_date_fin.
    
    date_freq:
        Interval for date label.
        "MS": every first day of the month.
        "14D": 14-day interval.
        "7D": 7-day interval.

    date_format:
        Date format. The default is yyyy-mm-dd.
    """

    lane_colors = [
        "rgba(68, 114, 196, 0.055)",
        "rgba(112, 173, 71, 0.055)"
    ]

    #Prepares a common date scale.
    date_min = df[tag_date_start].min().normalize()
    date_max = df[tag_date_fin].max().normalize()

    tick_dates = pd.date_range(start=date_min,
                               end=date_max,
                               freq=date_freq)

    #If the starting day is not included in the tick_dates, the starting date of the project is added.
    if date_min not in tick_dates:
        tick_dates = tick_dates.insert(0, date_min)

    for lane_nr, (owner, group) in enumerate(df.groupby(tag_task_owner, sort=False)):
        y0 = float(group[tag_task_y].min())-0.45
        y1 = float(group[tag_task_y].max())+0.45
        center = (y0 + y1) / 2

        #background band for each organization (task owner)
        fig.add_hrect(
            y0=y0,
            y1=y1,
            fillcolor=lane_colors[
                lane_nr % len(lane_colors)
            ],
            line_width=0,
            layer='below'
        )

        #Bottom border line for each swim lane.
        fig.add_hline(
            y=y1,
            line_width = 1,
            line_color="rgba(90, 90, 90, 0.35)",
            layer="below"
        )


        #Organization name
        fig.add_annotation(
            x=-0.20,
            y=center,
            xref='paper',
            yref='y',
            text=f'<b>{owner}</b>',
            showarrow=False,
            xanchor="right",
            yanchor="middle",
            align="right",
            font={"size":12,
                  "color": "#303030"}
        )

        for tick_date in tick_dates:
            #adding dates for each swim lane
            fig.add_annotation(
                x=tick_date,
                y=y1,
                xref="x",
                yref="y",
                text=tick_date.strftime(date_format),
                showarrow=False,
                xanchor='center',
                yanchor='top',
                yshift=-3,
                font={
                    "size":8,
                    "color":"#707070"
                },
                bgcolor="rgba(255,255,255,0.78)",
                borderpad=1
            )

            #adding short scale symbol lines at the dates
            fig.add_shape(
                type='line',
                x0=tick_date,
                x1=tick_date,
                y0=y1-0.06,
                y1=y1+0.06,
                xref="x",
                yref='y',
                line={
                    'color':'rgba(90,90,90,0.55)',
                    'width':1
                },
                layer='above',
            )




    



def make_gantt_chart(
        data: dict[str, Any],
        show_dependencies:bool=True,
        show_lag:bool=True
) -> go.Figure:
    """Makes an interactive swim lane type Gantt chart."""
    df = prepare_dataframe(data)
    project_name = data.get(tag_task_name, 'Gantt chart')
    owner_colors ={
        "CSK":"#0000CD",
        "MSAT":"#B22222",
        "製造":"#ED7D31",
        "QC":"#32CD32",
        "QA":"#2E8B57",
        "業務": "#00BFFF"
    }

    fig = px.timeline(
        data_frame=df,
        x_start=tag_date_start,
        x_end=tag_date_fin,
        y=tag_task_y,
        color=tag_task_owner,
        text=tag_task_name,
        color_discrete_map=owner_colors,
        custom_data=[tag_task_id, tag_task_name, tag_task_owner, tag_caldays_needed,
                     tag_dep_start, tag_typ_start, tag_lag_start,
                     tag_dep_fin, tag_typ_fin, tag_preempt_fin,
                     tag_description, tag_flag_delay],
        title=f'{project_name} Gantt Chart',
        labels={tag_task_owner:'Organization'}
    )



def main()->None:
    input_json = Path("gantt.json")
    output_htmp = Path("gantt_swimlane.html")

    data = load_gantt_json(input_json)

